### ISSUE TITLE
Fix: Error when running Vitest

### ISSUE THREAD

**Issue by teplostanski** [karpov-kir/the-software-essentialist-course#10]
https://github.com/karpov-kir/the-software-essentialist-course/blob/f1bbf6e6a432c0f91bf6f72dfc925b409890c34d/ThePhasesOfCraftship_mine/1_code_first/2ndAttempt/packages/frontend/vite.config.ts#L17

Hi!  

A new patch for `vite-plugin-pretty-module-classnames` has been released, fixing an issue that caused an error when running Vitest. We recommend updating the package to the latest version.  

Happy coding!

**Comment by teplostanski** [comment]
If you have any feedback or suggestions for improving `vite-plugin-pretty-module-classnames`, feel free to open an issue here: https://github.com/teplostanski/vite-plugin-pretty-module-classnames/issues/new  

I’d be happy to hear your thoughts!

**Comment by karpov-kir** [comment]
@teplostanski, great, thank you! I've updated the implementation in my repo  https://github.com/karpov-kir/the-software-essentialist-course/commit/4c1451da2f13dcdb4056105091a74b0bf0159b89. 🙏🏻
